const MyReviews = [
    {id:1, name: "Caleb Connor", career:"Web Developer", image:"https://images.pexels.com/photos/7605193/pexels-photo-7605193.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"I haven’t dug in, but I've played around a bit. It's really nice, and the developers are killing it—new features every week."},
    {id:2, name: "Olivia Smith", career:"Cloud Architect", image:"https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"It's so great! The devs are really talented, and clearly listening to feedback. They solicit and respond to ideas and comments in the forums all the time, which makes it feel very community-driven and collaborative"},
    {id:3, name: "Liam Smith", career:"DeVops Engineer", image:"https://images.pexels.com/photos/7504864/pexels-photo-7504864.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"I signed up yesterday and I'm totally sold. I've never been this excited about joining a new product since I joined Telegram."},
    {id:4, name: "Theodore Forbis", career:"Kotlin Developer", image:"https://images.pexels.com/photos/3241793/pexels-photo-3241793.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"The interface is breathtaking...but more importantly, there are no wasted features or placements. And to have every functionality available from the get-go is more than I ever bargained for."},
    {id:5, name: "Marie Broadbet ", career:"Graphic Designer", image:"https://images.pexels.com/photos/3752589/pexels-photo-3752589.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940", review:"It is not the app for me. There’s no flexibility in its use. It demands you use the app in their very narrow specific ways or you can’t use it."},
    {id:6, name: "Alex Brown", career:"UX Designer", image:"https://images.pexels.com/photos/7605818/pexels-photo-7605818.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:" I really, really dislike it. I find it buggy, confusing, complex, poorly-designed from an information architecture standpoint, and more. When assessing potential PM tools last year, ClickUp was at the bottom of my list, along with Asana."},
    {id:7, name: "Rick Novok", career:"Software Engineer", image:"https://images.pexels.com/photos/5483063/pexels-photo-5483063.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"We are a finance company, and not everyone is super tech savy, but everyone has found clickup easy to grasp. We use it both for recurring tasks for our leadership team, plus ad hoc projects"},
    {id:8, name: "Susan Barr", career:"Project Manager", image:"https://images.pexels.com/photos/6552749/pexels-photo-6552749.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"One big draw-back is the way that ClickUp is very much focussed and based for use by teams. For example, I have no need or interest in the concept of assigning tasks or having different spaces for teams."},
    {id:9, name: "Margaret Johnson", career:"Data Analyst", image:"https://images.pexels.com/photos/3228834/pexels-photo-3228834.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"I could have written this post and am in the process of starting over with a clean slate. To me, this is a problem with a lot of productivity apps out there. They are designed for teams. There are a lot of us that work as individuals."},
    {id:10, name: "Marlene Donahue", career:"System Architect", image:"https://images.pexels.com/photos/2728875/pexels-photo-2728875.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500", review:"wonderful interface, fast, reaching out to them I was able to negotiate $3.25/mo/person if we signup 30 person and a year in advance, great price but I can't do annual memberships. The interface is also a bit complex for our use, but definitely simpler than most. It's also fast"}
]

export default MyReviews
    
